[config]
name = "us"
desc = "English (US)"

[rows]
    e = [ '1', '2', '3', '4', '5', '6', '7', '8'    , '9'       , '0'           , 'minus'       , 'equal' ]
    d = [ 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i'    , 'o'       , 'p'           , 'bracketleft' , 'bracketright' ]
    c = [ 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k'    , 'l'       , 'semicolon'   , 'apostrophe' ]
    b = [ 'z', 'x', 'c', 'v', 'b', 'n', 'm', 'comma', 'period'  , 'slash' ]

    [rows.misc]
    BKSL = "backslash"
    TLDE = "grave"
