[rows]
    [rows.e]
    key-1 = "1"
    key-2 = "2"
    key-3 = "3"
    key-4 = "4"
    key-5 = "5"
    key-6 = "6"
    key-7 = "7"
    key-8 = "8"
    key-9 = "9"
    key-10 = "10"
    key-11 = "11"
    key-12 = "12"

    [rows.d]
    key-1 = "q"
    key-2 = "w"
    key-3 = "e"
    key-4 = "r"
    key-5 = "t"
    key-6 = "y"
    key-7 = "u"
    key-8 = "i"
    key-9 = "o"
    key-10 = "p"
    key-11 = "["
    key-12 = "]"

    [rows.c]
    key-1 = "a"
    key-2 = "s"
    key-3 = "d"
    key-4 = "f"
    key-5 = "g"
    key-6 = "h"
    key-7 = "j"
    key-8 = "k"
    key-9 = "l"
    key-10 = ";"
    key-11 = "'"

    [rows.b]
    key-1 = "z"
    key-2 = "x"
    key-3 = "c"
    key-4 = "v"
    key-5 = "b"
    key-6 = "n"
    key-7 = "m"
    key-8 = ","
    key-9 = "."
    key-10 = "/"

    [rows.misc]
    BKSL = "\\"
